<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EMEA-TUN-LP0975" name="unit.UnitTestWithDataProviders" tests="1" failures="0" timestamp="22 janv. 2024 17:34:52 GMT" time="0.000" errors="1">
  <testcase name="emptyUserThrowsException" time="0.000" classname="unit.UnitTestWithDataProviders">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: emptyUserThrowsException([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) john@emailcom,(java.lang.String) merry@company.com,(java.lang.String) soulou@yahoo.com]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: emptyUserThrowsException([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) john@emailcom,(java.lang.String) merry@company.com,(java.lang.String) soulou@yahoo.com]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.infinitest.testrunner.testng.TestNgRunner.runTest(TestNgRunner.java:82)
at org.infinitest.testrunner.DefaultRunner.runTest(DefaultRunner.java:60)
at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:71)
at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:116)
at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:93)
]]>
    </error>
  </testcase> <!-- emptyUserThrowsException -->
</testsuite> <!-- unit.UnitTestWithDataProviders -->
